[project]
name = "hikari-bot-official"
version = "0.2.9"
description = "Nonebot2 HikariBot For QQ-Official,支持战舰世界水表查询"
authors = [
    {name = "benx1n", email = "shirakamikanade@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11,<3.13"
keywords = ["nonebot", "nonebot2", "qqbot", "wows", "wws", "bot", "stats"]
dependencies = [
    "nonebot2[fastapi,websockets,httpx] >=2.5.0",
    "nonebot-adapter-qq >=1.2.0",
    "orjson >=3.8.11",
    "oss2 >=2.18.3",
    "httpx[http2] >=0.28.1",
    "asyncio >=3.4.3",
    "APScheduler >=3.10.1",
    "jinja2 >=3.0.0",
    "pydantic >=2.13.4",
    "playwright >=1.40.0",
    "aiofiles >=0.8.0",
    "beautifulsoup4 >=4.12.2",
    "loguru >=0.7.0",
    "json_tools >=0.4.1",
    "pytz >=2025.2",
    "pillow >=9.5.0",
    "nb-cli >=1.7.4"
]

[project.urls]
homepage = "https://github.com/benx1n/HikariBot-Official"
repository = "https://github.com/benx1n/HikariBot-Official"

[tool.poetry]
packages = [
    { include = "hikari_bot_official", from = "hikari_bot/plugins"}
]

[tool.nonebot]
plugin_dirs = ["hikari_bot/plugins"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "primary"
[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "supplemental"
[[tool.poetry.source]]
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core>=2.4.0"]
build-backend = "poetry.core.masonry.api"

# 以下工具配置保持不变
[tool.isort]
profile = "black"

[tool.black]
line-length = 150
skip-string-normalization = true

[tool.ruff]
line-length = 150
respect-gitignore = true
ignore-init-module-imports = true
select = [
    'F', 'E', 'W', 'I', 'C', 'B', 'Q', 'PL', 'RUF'
]
ignore = [
    'E501', 'RUF001', 'RUF002', 'RUF003', 'PLR2004',
    'C901', 'PLR0912', 'PLR0911', 'PLW0603'
]
flake8-quotes = {inline-quotes = 'single', multiline-quotes = 'double'}